# Generated by Django 3.1.2 on 2020-12-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201202_1718'),
        ('items', '0003_auto_20201130_2222'),
    ]

    operations = [
    ]
