# Generated by Django 3.1.2 on 2020-10-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_type', models.CharField(default='N/A', max_length=50)),
                ('document_number', models.CharField(default='N/A', max_length=200)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('site', models.URLField(null=True)),
                ('contact_name', models.CharField(max_length=150, null=True)),
                ('contac_email', models.EmailField(max_length=254, null=True)),
                ('contact_phone', models.PositiveIntegerField(null=True)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLoadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('inventoryLoad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryLoads.inventoryload')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item')),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryload',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventoryLoads.provider'),
        ),
    ]
