# Generated by Django 3.1.2 on 2020-10-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryLoads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryload',
            name='document_number',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryload',
            name='document_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
