# Generated by Django 3.1.2 on 2020-12-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryLoads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
