# Generated by Django 3.1.2 on 2020-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryLoads', '0002_auto_20201207_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_user_update',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
