# Generated by Django 3.1.2 on 2020-10-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryLoads', '0002_auto_20201012_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryloaddetail',
            name='InventoryLoad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryLoads.inventoryload'),
        ),
    ]
