# Generated by Django 3.1.2 on 2020-10-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryLoads', '0003_inventoryloaddetail_inventoryload'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryload',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryLoads.provider'),
        ),
    ]
