# Generated by Django 3.1.2 on 2020-10-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryLoads', '0005_auto_20201012_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryloaddetail',
            old_name='InventoryLoad',
            new_name='inventoryLoad',
        ),
    ]
