# Generated by Django 3.1.2 on 2020-10-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=145)),
                ('rush_order', models.BooleanField(default=True)),
                ('order_description', models.TextField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delibery_date', models.DateField()),
                ('state', models.CharField(max_length=11)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('last_date_update', models.DateField(auto_now=True)),
                ('basquet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.basket')),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('delibery_date', models.DateField()),
                ('phone', models.CharField(max_length=25)),
                ('zip_nubmer', models.SmallIntegerField()),
                ('address1', models.TextField(max_length=800)),
                ('city', models.CharField(max_length=50)),
                ('notes', models.TextField(verbose_name=500)),
                ('company_name', models.CharField(max_length=150)),
                ('last_date_update', models.DateField(auto_now=True)),
                ('delibery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.deliverytype')),
                ('last_user_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
