# Generated by Django 3.1.2 on 2020-10-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delibery',
            new_name='Delivery',
        ),
        migrations.RenameModel(
            old_name='DeliberyType',
            new_name='DeliveryType',
        ),
    ]
